blank_issues_enabled: false
contact_links:
  - name: Question and Answers
    url: https://github.com/pendingintent/soa-workbench/discussions/categories/q-a
    about: Please ask (or answer) any general user questions here.
